### PR TITLE
feat: responsive page layout

### LINKED ISSUE #786: Provide responsive design for Backend.AI GUI console
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
There's some cases that user access to Backend.AI GUI Console with mobile devices or tablet PC.
When It comes to mobile page, the layout should be different from layout for web browser for PC,
For example, long width of table makes user hard find out information in the screen unless user scrolls horizontally.

**Describe the solution you'd like**
Responsible design for Backend.AI GUI Console should provide those features.
- navigation side bar using modal UI
- mobile optimized panel layout for each menu page.
- top-app-bar should be simplified. For example using icons with dropdown is advised.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by lizable**
This PR resolves #786.

### CODE REVIEW

**Comment by inureyes** [comment]
image

**Comment by inureyes** [comment]
Also, session launch dialog has scrollbar. @lizable

**Comment by inureyes** [comment]
> Also, session launch dialog has scrollbar. @lizable

Nevermind. it was due to my small screen.

**Comment by lizable** [comment]
About the text-overflow in dropdown UI of resource group, I fixed it and pushed a commit for that.

**Review by adrysn — APPROVED** [review]
LTGM.

**Review by inureyes — APPROVED** [review]

**Pull request merged**
