### PR TITLE
fix: replace session name with session id (uuid)

### PR DESCRIPTION
**Pull request by adrysn**
This PR resolves https://github.com/lablup/backend.ai-console/issues/687.

I think we don't need to change WSProxy for this to work.

Internal ticket: OP#773.

### CODE REVIEW

**Comment by adrysn** [comment]
It seems like 502 error page is more frequently appears. I'll look into this PR more.

**Comment by adrysn** [comment]
> It seems like 502 error page is more frequently appears. I'll look into this PR more.

Hmm. It is not reproduced any more...

**Comment by lizable** [comment]
This happens to me quite often, too. 😭
I guess something goes wrong when executing many apps at the same time.

**Comment by adrysn** [comment]
Fixed initial 502 error.

**Review by inureyes — APPROVED** [review]
LGTM.

**Pull request merged**
