### PR TITLE
feat: alert file extension change

### LINKED ISSUE #803: Let's show an alert message when user rename the file including file extension in the Vfolder.
**Is your feature request related to a problem? Please describe.**
For now, there's a high chance of mistakes can be taken when the user trying to rename a file in vfolder,
since it isn't preserved the file extension, but it can be changed completely according to user's input.
For example, when the user uploads an image file named ```foo.png```, and changes it with ```bar.txt``` or ```bar.mp4``` or even ```bar```(no file extension, just a plain file).
It will confuses the user after all, unless there's any warning message before changing the file extension.

**Describe the solution you'd like**
If user tries to change the file name including file extension, a warning modal to notice the user what will be changed.

**Describe alternatives you've considered**
Just a simple name changing probably doesn't need any notice dialog before changing request is sent to the server.
(e.g. foo.png -> bar.png)
If user renames the file without any single dot, the purpose is simply renaming, mostly.
Therefore we should follow this tendency in order to make a natural user experience.

### PR DESCRIPTION
**Pull request by lizable**
This PR resolves #803.

### CODE REVIEW

**Review by adrysn — COMMENTED** [review]
How can I remove the extension of a file'? For example, `test.py` -> `test`?

**Comment by lizable** [comment]
Now when users try to rename a file without a file extension, they can decide whether to simply rename the file or delete the file extension.

**Review by adrysn — CHANGES_REQUESTED** [review]
I found one problems.

* Unable to rename directories.
  image

**Comment by inureyes** [comment]
@lizable Please check the directory name modification issue.

**Comment by lizable** [comment]
> I found one problems.
> 
> * Unable to rename directories.
>   image

This problem is related to [manager#397](https://github.com/lablup/backend.ai-manager/pull/397) and [storage-proxy#18](https://github.com/lablup/backend.ai-storage-proxy/pull/18), since those renaming directory feature is WIP.
It will be resolved after those PRs are merged into the master branch of each repository.

**Review by adrysn — APPROVED** [review]
LGTM.

**Pull request merged**
