### PR TITLE
fix: enable export csv in session page.

### LINKED ISSUE #739: exporting CSV in Sessions page doesn't work.
**Describe the bug**
When the user tries to export CSV file of the session list, it throws an error.
**To Reproduce**
※ NOTICE:
Only admin and super-admin account have an access to 'export CSV' in the sesssions page.
1. Go to backend.ai meta repository and download install-dev.sh in scripts directory
2. Execute install-dev.sh in the terminal and follow the instruction to execute both agent and manager in local after when installation is done.
3. Execute backend.ai console. (see the README.md of backend.ai-console repository)
4. Go to sessions page.
5. Click '...' button.
6. Click export csv button in the dropdown menu.
7. dialog pops up.
8. click export csv button in the dialog.
9. Error occurs.
(Error message when clicks 'export csv': backend.ai-client-es6.js:1 Uncaught (in promise) TypeError: this.client.gql is not a function)

**Expected behavior**
If the user clicks export csv file, it should be downloaded immediately.

Internal ticket: OP#832.

### PR DESCRIPTION
**Pull request by lizable**
This PR resolves #739.

### CODE REVIEW

**Comment by inureyes** [comment]
@lizable It does not start downloading (tested with Firefox 82)

**Comment by inureyes** [comment]
> @lizable It does not start downloading (tested with Firefox 82)

@lizable  query is working and response is working but downloading is not working.

**Comment by lizable** [comment]
@inureyes I also checked in firefox browser with same version that you mentioned, and I found out that downloading feature is working, but it doesn't put the file extension at the end of the file.
(Meanwhile, Chrome and Safari browser doesn't have this issue.)
I fixed this, so I wonder If you could check the download operation works well.

**Review by inureyes — APPROVED** [review]
LGTM

**Pull request merged**
